---
name: Geo-JapanMesh
version: 0.0.2
author:
  - 'OHTSUKA Ko-hei <nene@kokogiko.net>'
abstract: Convert between latitude/longitude and Japanese geographical mesh code
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Exporter: 0
  Test::Base: 0
  version: 0
provides:
  Geo::JapanMesh:
    file: lib/Geo/JapanMesh.pm
    version: 0.0.2
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
